name: Setup PostgreSQL dev and pg_config
description: Installs PostgreSQL client/server dev headers and exports PG_CONFIG
inputs:
  pg-major:
    description: "Preferred PostgreSQL major version"
    required: false
    default: "17"
runs:
  using: composite
  steps:
    - name: Install PostgreSQL dev and set PG_CONFIG
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${RUNNER_OS}" == "Linux" ]]; then
          sudo apt-get update
          sudo install -d -m 0755 /usr/share/keyrings
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-${{ inputs.pg-major }} postgresql-server-dev-${{ inputs.pg-major }} || \
          sudo apt-get install -y postgresql-16 postgresql-server-dev-16 || \
          sudo apt-get install -y postgresql-15 postgresql-server-dev-15
          echo "PG_CONFIG=$(command -v pg_config)" >> "$GITHUB_ENV"
        elif [[ "${RUNNER_OS}" == "macOS" ]]; then
          brew update
          brew install postgresql@${{ inputs.pg-major }}
          if brew list postgresql@${{ inputs.pg-major }} &>/dev/null; then
            echo "PG_CONFIG=$(brew --prefix postgresql@${{ inputs.pg-major }})/bin/pg_config" >> "$GITHUB_ENV"
          elif brew list postgresql@16 &>/dev/null; then
            echo "PG_CONFIG=$(brew --prefix postgresql@16)/bin/pg_config" >> "$GITHUB_ENV"
          else
            echo "pg_config not found on macOS" >&2
            exit 1
          fi
        else
          echo "Unsupported OS: ${RUNNER_OS}" >&2
          exit 1
        fi
